import type { Metadata } from "next";
import Navbar from "@/components/ui/navbar";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`antialiased bg-white min-h-screen`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
